# Welcome to Jekyll!
#

# Site settings
title: EdIntelligence's AI Careers Fair
description: |
  19th of June 2018  
  Informatics Forum G.07  
  The University of Edinburgh
owner: Martin Asenov # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: m.asenov@ed.ac.uk
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://edintelligence.github.io/fair"
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  connectdevelop: https://edintelligence.github.io/
  facebook-official: https://www.facebook.com/groups/1492448401050643
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
